
import { Logo } from '@/components/logo';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <header className="sticky top-0 z-50 flex h-16 items-center justify-between border-b bg-background/95 px-4 backdrop-blur-sm md:px-6">
        <Link href="/" className="flex items-center gap-2" prefetch={false}>
          <Logo className="h-8 w-8 text-primary" />
          <span className="font-headline text-lg font-semibold">UGO AI Studio</span>
        </Link>
        <Button asChild>
          <Link href="/">Back to Home</Link>
        </Button>
      </header>
      <main className="flex-1">
        <section className="py-20 md:py-32">
          <div className="container mx-auto max-w-4xl px-4 md:px-6">
            <div className="prose prose-lg dark:prose-invert mx-auto">
              <h1 className="font-headline text-4xl font-bold tracking-tighter sm:text-5xl">Terms of Service</h1>
              <p className="lead mt-4 text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
              
              <h2>1. Acceptance of Terms</h2>
              <p>
                By accessing and using UGO AI Studio (the "Service"), you accept and agree to be bound by the terms and
                provision of this agreement. In addition, when using these particular services, you shall be subject to
                any posted guidelines or rules applicable to such services. Any participation in this service will
                constitute acceptance of this agreement.
              </p>

              <h2>2. Description of Service</h2>
              <p>
                UGO AI Studio is an AI-powered platform for content creation, application development, and workflow automation.
                The Service is provided "as is" and the owner of this Service, Ugochukwu Jonathan, assumes no responsibility
                for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings.
              </p>

              <h2>3. User Conduct</h2>
              <p>
                You agree not to use the Service to create, upload, or share any content that is unlawful, harmful,
                threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable. You are
                solely responsible for the content you generate and the consequences of sharing it.
              </p>

              <h2>4. Intellectual Property</h2>
              <p>
                The Service and its original content, features, and functionality are owned by Ugochukwu Jonathan and
                are protected by international copyright, trademark, patent, trade secret, and other intellectual
                property or proprietary rights laws. Content generated by you remains your property, but you grant
                UGO AI Studio a license to use it to provide and improve the service.
              </p>
              
              <h2>5. Limitation of Liability</h2>
              <p>
                In no event shall Ugochukwu Jonathan, nor its directors, employees, partners, agents, suppliers, or
                affiliates, be liable for any indirect, incidental, special, consequential or punitive damages,
                including without limitation, loss of profits, data, use, goodwill, or other intangible losses,
                resulting from your access to or use of or inability to access or use the Service.
              </p>
              
              <h2>6. Changes to Terms</h2>
              <p>
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will
                provide notice of any changes by posting the new Terms of Service on this page.
              </p>

              <h2>7. Contact Us</h2>
              <p>
                If you have any questions about these Terms, please contact us through the developer's portfolio.
              </p>
            </div>
          </div>
        </section>
      </main>
      <footer className="border-t bg-secondary">
        <div className="container mx-auto flex flex-col items-center justify-between gap-4 px-4 py-8 md:flex-row md:px-6">
          <div className="flex items-center gap-2">
            <Logo className="h-6 w-6 text-muted-foreground" />
            <span className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} UGO AI Studio made by{' '}
              <a
                href="https://ugoyoungking.github.io/portfolio/"
                target="_blank"
                rel="noopener noreferrer"
                className="underline text-primary hover:text-primary/80"
              >
                Ugoyoungking
              </a>
            </span>
          </div>
          <nav className="flex gap-4 sm:gap-6">
            <Link href="/terms" className="text-sm hover:underline" prefetch={false}>
              Terms
            </Link>
            <Link href="/privacy" className="text-sm hover:underline" prefetch={false}>
              Privacy
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
